# Generated by Django 6.0.3 on 2026-04-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_memberprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='affiliation_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='ranking',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('admin', 'Admin')], default='member', max_length=20),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
