# Generated by Django 6.0.3 on 2026-05-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='number',
        ),
        migrations.AddField(
            model_name='court',
            name='name',
            field=models.CharField(default='Terrain A', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
