# Generated by Django 6.0.3 on 2026-05-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_remove_court_number_court_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='type',
            field=models.CharField(choices=[('simple', 'Simple'), ('double', 'Double'), ('blocage_admin', 'Blocage Admin')], default='simple', max_length=20),
        ),
    ]
