# Generated by Django 6.0.3 on 2026-06-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_reservation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
